CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.telemetry_lap_summary (
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    lap_number INTEGER NOT NULL,
    sample_count BIGINT NOT NULL,
    max_speed_kmh DOUBLE PRECISION,
    average_speed_kmh DOUBLE PRECISION,
    average_rpm DOUBLE PRECISION,
    telemetry_start TIMESTAMPTZ,
    telemetry_end TIMESTAMPTZ,
    PRIMARY KEY (session_key, driver_number, lap_number)
);

CREATE TABLE IF NOT EXISTS analytics.session_summary (
    session_key BIGINT PRIMARY KEY,
    session_type TEXT NOT NULL,
    session_name TEXT NOT NULL,
    date_start TIMESTAMPTZ NOT NULL,
    date_end TIMESTAMPTZ NOT NULL,
    meeting_key BIGINT NOT NULL,
    circuit_key BIGINT NOT NULL,
    circuit_short_name TEXT NOT NULL,
    country_key BIGINT NOT NULL,
    country_code TEXT NOT NULL,
    country_name TEXT NOT NULL,
    location TEXT NOT NULL,
    gmt_offset TEXT NOT NULL,
    year INTEGER NOT NULL,
    is_cancelled BOOLEAN NOT NULL,
    driver_count INTEGER NOT NULL,
    lap_record_count INTEGER NOT NULL,
    car_data_record_count INTEGER NOT NULL,
    team_radio_record_count INTEGER NOT NULL,
    telemetry_driver_count INTEGER NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    source_file TEXT,
    source_path TEXT,
    ingestion_run_id TEXT
);

CREATE TABLE IF NOT EXISTS analytics.driver_session_performance (
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    full_name TEXT NOT NULL,
    name_acronym TEXT NOT NULL,
    team_name TEXT NOT NULL,
    team_colour TEXT,
    first_name TEXT,
    last_name TEXT NOT NULL,
    lap_count INTEGER NOT NULL,
    complete_lap_count INTEGER NOT NULL,
    pit_out_lap_count INTEGER NOT NULL,
    best_lap_duration_s DOUBLE PRECISION,
    average_lap_duration_s DOUBLE PRECISION,
    best_duration_sector_1_s DOUBLE PRECISION,
    best_duration_sector_2_s DOUBLE PRECISION,
    best_duration_sector_3_s DOUBLE PRECISION,
    max_i1_speed_kmh DOUBLE PRECISION,
    max_i2_speed_kmh DOUBLE PRECISION,
    max_st_speed_kmh DOUBLE PRECISION,
    telemetry_sample_count INTEGER NOT NULL,
    telemetry_start TIMESTAMPTZ,
    telemetry_end TIMESTAMPTZ,
    max_speed_kmh DOUBLE PRECISION,
    average_speed_kmh DOUBLE PRECISION,
    max_rpm DOUBLE PRECISION,
    average_rpm DOUBLE PRECISION,
    average_throttle DOUBLE PRECISION,
    brake_pressed_sample_count INTEGER NOT NULL,
    drs_active_sample_count INTEGER NOT NULL,
    drs_active_percentage DOUBLE PRECISION,
    radio_message_count INTEGER NOT NULL,
    first_radio_at TIMESTAMPTZ,
    last_radio_at TIMESTAMPTZ,
    meeting_key BIGINT NOT NULL,
    session_type TEXT NOT NULL,
    session_name TEXT NOT NULL,
    circuit_short_name TEXT NOT NULL,
    country_name TEXT NOT NULL,
    year INTEGER NOT NULL,
    date_start TIMESTAMPTZ NOT NULL,
    date_end TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (session_key, driver_number)
);

CREATE TABLE IF NOT EXISTS analytics.telemetry_summary (
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    telemetry_sample_count INTEGER NOT NULL,
    telemetry_start TIMESTAMPTZ,
    telemetry_end TIMESTAMPTZ,
    max_speed_kmh DOUBLE PRECISION,
    average_speed_kmh DOUBLE PRECISION,
    max_rpm DOUBLE PRECISION,
    average_rpm DOUBLE PRECISION,
    average_throttle DOUBLE PRECISION,
    brake_pressed_sample_count INTEGER NOT NULL,
    drs_active_sample_count INTEGER NOT NULL,
    drs_active_percentage DOUBLE PRECISION,
    PRIMARY KEY (session_key, driver_number)
);

CREATE TABLE IF NOT EXISTS analytics.lap_performance (
    meeting_key BIGINT NOT NULL,
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    lap_number INTEGER NOT NULL,
    date_start TIMESTAMPTZ,
    duration_sector_1 DOUBLE PRECISION,
    duration_sector_2 DOUBLE PRECISION,
    duration_sector_3 DOUBLE PRECISION,
    i1_speed DOUBLE PRECISION,
    i2_speed DOUBLE PRECISION,
    is_pit_out_lap BOOLEAN,
    lap_duration DOUBLE PRECISION,
    segments_sector_1 JSONB,
    segments_sector_2 JSONB,
    segments_sector_3 JSONB,
    st_speed DOUBLE PRECISION,
    source_file TEXT,
    source_path TEXT,
    ingestion_run_id TEXT,
    sector_time_sum_s DOUBLE PRECISION,
    is_complete_lap BOOLEAN,
    driver_best_lap_duration_s DOUBLE PRECISION,
    delta_to_driver_best_lap_s DOUBLE PRECISION,
    full_name TEXT,
    name_acronym TEXT,
    team_name TEXT,
    team_colour TEXT,
    first_name TEXT,
    last_name TEXT,
    PRIMARY KEY (session_key, driver_number, lap_number)
);

CREATE TABLE IF NOT EXISTS analytics.radio_summary (
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    radio_message_count INTEGER NOT NULL,
    first_radio_at TIMESTAMPTZ,
    last_radio_at TIMESTAMPTZ,
    PRIMARY KEY (session_key, driver_number)
);

CREATE TABLE IF NOT EXISTS analytics.drs_state_summary (
    session_key BIGINT NOT NULL,
    driver_number INTEGER NOT NULL,
    drs INTEGER NOT NULL,
    sample_count INTEGER NOT NULL,
    full_name TEXT,
    name_acronym TEXT,
    team_name TEXT,
    team_colour TEXT,
    first_name TEXT,
    last_name TEXT,
    PRIMARY KEY (session_key, driver_number, drs)
);
